#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _dcn_CaConc_reg();
extern void _dcn_CaHVA_reg();
extern void _dcn_CaLVA_reg();
extern void _dcn_CalConc_reg();
extern void _dcn_NaF_reg();
extern void _dcn_NaP_reg();
extern void _dcn_SK_reg();
extern void _dcn_TNC_reg();
extern void _dcn_fKdr_reg();
extern void _dcn_h_reg();
extern void _dcn_pas_reg();
extern void _dcn_sKdr_reg();
extern void _grl_goc_reg();
extern void _grl_grc_reg();
extern void _grl_stellc_reg();
extern void _io_ca_reg();
extern void _io_gap_reg();
extern void _io_h_reg();
extern void _io_kdr_reg();
extern void _io_na_reg();
extern void _mc_Cad_reg();
extern void _mc_IM_reg();
extern void _mc_IT_reg();
extern void _mc_hh2_reg();
extern void _noisycurrent_reg();
extern void _noisyexp2syn_reg();
extern void _noisyexpsyn_reg();
extern void _noisytanhsyn_reg();
extern void _noisytanhsyn2_reg();
extern void _pc_CaBK_reg();
extern void _pc_CaP_reg();
extern void _pc_Caint_reg();
extern void _pc_Ihcn_reg();
extern void _pc_Kbin_reg();
extern void _pc_Kv1_reg();
extern void _pc_Kv4_reg();
extern void _pc_Na_reg();
extern void _pc_Narsg_reg();
extern void _pc_leak_reg();
extern void _sinclamp_reg();
extern void _tc_CaConc_reg();
extern void _tc_CaT_reg();
extern void _tc_fastK_reg();
extern void _tc_fastNa_reg();
extern void _tc_h_reg();
extern void _tc_pas2_reg();
extern void _tc_slowK_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," dcn_CaConc.mod");
fprintf(stderr," dcn_CaHVA.mod");
fprintf(stderr," dcn_CaLVA.mod");
fprintf(stderr," dcn_CalConc.mod");
fprintf(stderr," dcn_NaF.mod");
fprintf(stderr," dcn_NaP.mod");
fprintf(stderr," dcn_SK.mod");
fprintf(stderr," dcn_TNC.mod");
fprintf(stderr," dcn_fKdr.mod");
fprintf(stderr," dcn_h.mod");
fprintf(stderr," dcn_pas.mod");
fprintf(stderr," dcn_sKdr.mod");
fprintf(stderr," grl_goc.mod");
fprintf(stderr," grl_grc.mod");
fprintf(stderr," grl_stellc.mod");
fprintf(stderr," io_ca.mod");
fprintf(stderr," io_gap.mod");
fprintf(stderr," io_h.mod");
fprintf(stderr," io_kdr.mod");
fprintf(stderr," io_na.mod");
fprintf(stderr," mc_Cad.mod");
fprintf(stderr," mc_IM.mod");
fprintf(stderr," mc_IT.mod");
fprintf(stderr," mc_hh2.mod");
fprintf(stderr," noisycurrent.mod");
fprintf(stderr," noisyexp2syn.mod");
fprintf(stderr," noisyexpsyn.mod");
fprintf(stderr," noisytanhsyn.mod");
fprintf(stderr," noisytanhsyn2.mod");
fprintf(stderr," pc_CaBK.mod");
fprintf(stderr," pc_CaP.mod");
fprintf(stderr," pc_Caint.mod");
fprintf(stderr," pc_Ihcn.mod");
fprintf(stderr," pc_Kbin.mod");
fprintf(stderr," pc_Kv1.mod");
fprintf(stderr," pc_Kv4.mod");
fprintf(stderr," pc_Na.mod");
fprintf(stderr," pc_Narsg.mod");
fprintf(stderr," pc_leak.mod");
fprintf(stderr," sinclamp.mod");
fprintf(stderr," tc_CaConc.mod");
fprintf(stderr," tc_CaT.mod");
fprintf(stderr," tc_fastK.mod");
fprintf(stderr," tc_fastNa.mod");
fprintf(stderr," tc_h.mod");
fprintf(stderr," tc_pas2.mod");
fprintf(stderr," tc_slowK.mod");
fprintf(stderr, "\n");
    }
_dcn_CaConc_reg();
_dcn_CaHVA_reg();
_dcn_CaLVA_reg();
_dcn_CalConc_reg();
_dcn_NaF_reg();
_dcn_NaP_reg();
_dcn_SK_reg();
_dcn_TNC_reg();
_dcn_fKdr_reg();
_dcn_h_reg();
_dcn_pas_reg();
_dcn_sKdr_reg();
_grl_goc_reg();
_grl_grc_reg();
_grl_stellc_reg();
_io_ca_reg();
_io_gap_reg();
_io_h_reg();
_io_kdr_reg();
_io_na_reg();
_mc_Cad_reg();
_mc_IM_reg();
_mc_IT_reg();
_mc_hh2_reg();
_noisycurrent_reg();
_noisyexp2syn_reg();
_noisyexpsyn_reg();
_noisytanhsyn_reg();
_noisytanhsyn2_reg();
_pc_CaBK_reg();
_pc_CaP_reg();
_pc_Caint_reg();
_pc_Ihcn_reg();
_pc_Kbin_reg();
_pc_Kv1_reg();
_pc_Kv4_reg();
_pc_Na_reg();
_pc_Narsg_reg();
_pc_leak_reg();
_sinclamp_reg();
_tc_CaConc_reg();
_tc_CaT_reg();
_tc_fastK_reg();
_tc_fastNa_reg();
_tc_h_reg();
_tc_pas2_reg();
_tc_slowK_reg();
}
